// piblockly/media/user_modules/_core_hw_lib/zh-hant.js

export const MSG_PIBLOCKLY_HW_ZH_HANT = {
  // Color Keys
  "PIBLOCKLY_HW_COLOR_SENSORS": "#4A90E2",
  "PIBLOCKLY_HW_COLOR_ACTUATORS": "#D9A443",
  "PIBLOCKLY_HW_COLOR_AI": "#8BC34A",

  // Category Keys
  "PIBLOCKLY_HW_CATEGORY": "Hardware",

  //Sensors
  "PIBLOCKLY_HW_CATEGORY_SENSORS": "Sensors",

  // Actuators
  "PIBLOCKLY_HW_CATEGORY_ACTUATORS": "Actuators",

  // AI
  "PIBLOCKLY_HW_CATEGORY_AI": "AI",




  // Sensors
  // Common Category
  "PIBLOCKLY_HW_CATEGORY_COMMON": "Common",

  // Ultrasonic Distance Block
  "PIBLOCKLY_HW_ULTRASONIC_DISTANCE_MESSAGE": "HC-SR04 超音波測距，觸發腳位 %1，回聲腳位 %2",
  "PIBLOCKLY_HW_ULTRASONIC_DISTANCE_TOOLTIP": "讀取 HC-SR04 超音波感測器距離",
  "PIBLOCKLY_HW_ULTRASONIC_DISTANCE_HELPURL": "",

  // DHT Sensor Block
  "PIBLOCKLY_HW_DHT_READ_MESSAGE": "讀取 DHT %1 於腳位 %2，讀取: %3",
  "PIBLOCKLY_HW_DHT_READ_TOOLTIP": "從 DHT 感測器讀取溫度或濕度。需要安裝 Adafruit 的 'DHT sensor library' 函式庫。",
  "PIBLOCKLY_HW_DHT_TYPE_11": "DHT11",
  "PIBLOCKLY_HW_DHT_TYPE_22": "DHT22",
  "PIBLOCKLY_HW_DHT_READING_TEMP": "溫度 (°C)",
  "PIBLOCKLY_HW_DHT_READING_HUMIDITY": "濕度 (%)",


  // MPU9250 Blocks
  "PIBLOCKLY_HW_SENSORS_MPU9250": "MPU9250",
  "PIBLOCKLY_HW_MPU9250_INIT_MESSAGE": "初始化 MPU9250 (I2C) SDA %1 SCL %2 加速度計範圍 %3 陀螺儀範圍 %4",
  "PIBLOCKLY_HW_MPU9250_INIT_TOOLTIP": "初始化 MPU9250 感測器。設定 I2C 腳位，並啟動加速度計、陀螺儀和磁力計。",

  "PIBLOCKLY_HW_MPU9250_ACCEL_FETCH": "更新加速度感測資料",
  "PIBLOCKLY_HW_MPU9250_ACCEL_3AXIS": "加速度感測G值",
  "PIBLOCKLY_HW_MPU9250_3AXIS_POST_FIX": "軸",

  "PIBLOCKLY_HW_MPU9250_GYRO_FETCH": "更新陀螺儀感測資料",
  "PIBLOCKLY_HW_MPU9250_GYRO_3AXIS": "陀螺儀感測值",
  "PIBLOCKLY_HW_MPU9250_3AXIS_POST_FIX_UNIT": "角速度(DPS)",

  "PIBLOCKLY_HW_MPU9250_MAG_FETCH": "更新磁力感測資料",
  "PIBLOCKLY_HW_MPU9250_MAG_3AXIS": "磁力感測值",
  "PIBLOCKLY_HW_MPU9250_ACCEL_PITCH_ROLL": "旋轉角度",
  "PIBLOCKLY_HW_MPU9250_PITCH_ROLL_PITCH": "俯仰(Pitch)",
  "PIBLOCKLY_HW_MPU9250_PITCH_ROLL_ROLL": "翻滾(Roll)",

  "PIBLOCKLY_HW_MPU9250_ACCEL_FETCH_TOOLTIP": "更新MPU9250加速度感測器的數據。",
  "PIBLOCKLY_HW_MPU9250_ACCEL_3AXIS_TOOLTIP": "獲取MPU9250加速度感應器在X、Y、Z軸的G值。",
  "PIBLOCKLY_HW_MPU9250_ACCEL_PITCH_ROLL_TOOLTIP": "獲取MPU9250加速度感應器的俯仰(Pitch)或翻滾(Roll)角度。",

  "PIBLOCKLY_HW_MPU9250_MAG_FETCH_TOOLTIP": "更新MPU9250磁力感應器的數據。",
  "PIBLOCKLY_HW_MPU9250_MAG_3AXIS_TOOLTIP": "獲取MPU9250磁力感應器在X、Y、Z軸的磁力值。",

  "PIBLOCKLY_HW_MPU9250_GYRO_FETCH_TOOLTIP": "更新MPU9250陀螺儀的數據。",
  "PIBLOCKLY_HW_MPU9250_GYRO_3AXIS_TOOLTIP": "獲取MPU9250陀螺儀在X、Y、Z軸的角速度值。",



  // MAX30105 Blocks
  "PIBLOCKLY_HW_MAX30105_HELPURL": "",
  "PIBLOCKLY_HW_MAX30105_TITLE": "MAX30105血氧感測",
  "PIBLOCKLY_HW_MAX30105_TOOLTIP": "MAX30105 SPO2",
  "PIBLOCKLY_HW_MAX30105_INIT_TOOLTIP": "初始化 MAX30105 脈搏血氧感測器。可設定 I2C 腳位與紅光 LED 亮度。",
  "PIBLOCKLY_HW_MAX30105_CHECK_TOOLTIP": "偵測MAX30105血氧感測器是否感測到手指、感測器是否準備好或心跳。",
  "PIBLOCKLY_HW_MAX30105_GET_BEAT_RATE_TOOLTIP": "獲取MAX30105血氧感測器的平均心率。",
  "PIBLOCKLY_HW_MAX30105_GET_SPO2_TOOLTIP": "獲取MAX30105血氧感測器的血氧飽和度(SpO2)讀數。",
  "PIBLOCKLY_HW_MAX30105_GET_TEMPERATURE_TOOLTIP": "獲取MAX30105血氧感測器的溫度讀數。",
  "PIBLOCKLY_HW_MAX30105_SET_BEAT_RANGE_TOOLTIP": "設定MAX30105血氧感測器合理的心率偵測範圍。",
  "PIBLOCKLY_HW_MAX30105_SET_SPO2_CLEAR_TOOLTIP": "重設MAX30105血氧感測器已偵測到的血氧飽和度(SpO2)值。",

  "PIBLOCKLY_HW_MAX30105_LED": "紅色LED亮度",
  "PIBLOCKLY_HW_MAX30105_CHECK": "偵測到",
  "PIBLOCKLY_HW_MAX30105_CHECK_LIST": [["手指","IR"],["感測器","READY"],["心跳","HB"]],
  "PIBLOCKLY_HW_MAX30105_CHECK_MESSAGE": "MAX30105血氧感測 偵測到 %1 ?",
  "PIBLOCKLY_HW_MAX30105_WARNING": "必須先設定「" + "PIBLOCKLY_HW_MAX30105_TITLE" + " " + "PIBLOCKLY_HW_PROBBIE_INIT" + "\"」積木",
  "PIBLOCKLY_HW_MAX30105_BEATRATE": "心率",
  "PIBLOCKLY_HW_MAX30105_AVG": "次平均值",
  "PIBLOCKLY_HW_MAX30105_GET_BEAT_RATE_MESSAGE": "MAX30105血氧感測 心率%1次平均值 ",
  "PIBLOCKLY_HW_MAX30105_SPO2": "SpO2血氧飽和度",
  "PIBLOCKLY_HW_MAX30105_TEMPERATURE": "溫度",
  "PIBLOCKLY_HW_MAX30105_TEMP_LIST": [["攝氏","C"],["華氏","F"]],
  "PIBLOCKLY_HW_MAX30105_GET_TEMPERATURE_MESSAGE": "MAX30105血氧感測 溫度 %1",
  "PIBLOCKLY_HW_MAX30105_BEAT_RANGE": "設定合理偵測心率範圍",
  "PIBLOCKLY_HW_MAX30105_SET_BEAT_RANGE_MESSAGE": "MAX30105血氧感測 設定合理偵測心率範圍 %1 ~ %2",
  "PIBLOCKLY_HW_MAX30105_SPO2_CLEAR": "血氧SpO2感測資料重設",
  "PIBLOCKLY_HW_MAX30105_INIT_MESSAGE": "初始化 MAX30105 (I2C) SDA %1 SCL %2 LED 紅光亮度 %3",
  //"PIBLOCKLY_HW_PROBBIE_INIT": "初始化",

  // PS2 Blocks
  "PIBLOCKLY_HW_PS2": "PS2手把",
  "PIBLOCKLY_HW_PS2_INITIAL": "初始化",
  "PIBLOCKLY_HW_PS2_PRESSURES": "壓力靈敏度",
  "PIBLOCKLY_HW_PS2_RUMBLE": "振動回饋",
  "PIBLOCKLY_HW_PS2_READ_CONTROLLER": "讀取一次數據",
  "PIBLOCKLY_HW_PS2_VIBRATE_N": "關",
"PIBLOCKLY_HW_PS2_VIBRATE_Y": "開",
  "PIBLOCKLY_HW_PS2_VIBRATE_VALUE": "強度",
  "PIBLOCKLY_HW_PS2_READ_MESSAGE": "讀取PS2手把狀態 並設定馬達震動 %1 強度 %2",
  "PIBLOCKLY_HW_PS2_BUTTON_PRESS": "正按下",
  "PIBLOCKLY_HW_PS2_BUTTON_PRESS_NEW": "剛改變",
  "PIBLOCKLY_HW_PS2_BUTTON_PRESS_JUST": "剛按下",
  "PIBLOCKLY_HW_PS2_BUTTON_RELEASE_JUST": "剛放開",
  "PIBLOCKLY_HW_PS2_ENABLED": "啟用",
  "PIBLOCKLY_HW_PS2_INITIAL_FUNC_MESSAGE": "PS2手把 啟用 %1",
  "PIBLOCKLY_HW_PS2_DISABLED": "停用",
  "PIBLOCKLY_HW_PS2_STICK_LEFT": "左搖桿",
  "PIBLOCKLY_HW_PS2_STICK_RIGHT": "右搖桿",
  "PIBLOCKLY_HW_PS2_STICK_DIRECTION8": "八方位",
  "PIBLOCKLY_HW_PS2_STICK_DIRECTION4": "四方位",
  "PIBLOCKLY_HW_PS2_STICK_DIRECTION_UP": "↑",
  "PIBLOCKLY_HW_PS2_STICK_DIRECTION_UPRIGHT": "↗",
  "PIBLOCKLY_HW_PS2_STICK_DIRECTION_RIGHT": "→",
  "PIBLOCKLY_HW_PS2_STICK_DIRECTION_DOWNRIGHT": "↘",
  "PIBLOCKLY_HW_PS2_STICK_DIRECTION_DOWN": "↓",
  "PIBLOCKLY_HW_PS2_STICK_DIRECTION_DOWNLEFT": "↙",
  "PIBLOCKLY_HW_PS2_STICK_DIRECTION_LEFT": "←",
  "PIBLOCKLY_HW_PS2_STICK_DIRECTION_LEFTUP": "↖",
  "PIBLOCKLY_HW_PS2_STICK_DIRECTION_CENTER": "o",
  "PIBLOCKLY_HW_PS2_STICK_DIRECTION_MESSAGE": "PS2手把 %1 搖桿 %2 方向 %3",
  "PIBLOCKLY_HW_PS2_STATE": "開發板已連接接收器",
  "PIBLOCKLY_HW_PS2_RECEIVER_STATE": "接收器連接開發板中斷",
  "PIBLOCKLY_HW_PS2_ANALOG_MAX": "開發板類比輸入最大值",
  "PIBLOCKLY_HW_PS2_ANALOG_MAX_MESSAGE": "PS2手把 開發板類比輸入最大值 %1",
  "PIBLOCKLY_HW_PS2_ANALOG_READ_LX": "左搖桿X軸類比值",
  "PIBLOCKLY_HW_PS2_ANALOG_READ_LY": "左搖桿Y軸類比值",
  "PIBLOCKLY_HW_PS2_ANALOG_READ_LA": "左搖桿方位角",
  "PIBLOCKLY_HW_PS2_ANALOG_READ_RX": "右搖桿X軸類比值",
  "PIBLOCKLY_HW_PS2_ANALOG_READ_RY": "右搖桿Y軸類比值",
  "PIBLOCKLY_HW_PS2_ANALOG_READ_RA": "右搖桿方位角",
  "PIBLOCKLY_HW_PS2_ANALOG_READ_MESSAGE": "PS2手把 %1",
  "PIBLOCKLY_HW_PS2_BUTTON_GREEN": "△ 綠",
  "PIBLOCKLY_HW_PS2_BUTTON_RED": "○ 紅",
  "PIBLOCKLY_HW_PS2_BUTTON_BLUE": "✕ 藍",
  "PIBLOCKLY_HW_PS2_BUTTON_PINK": "☐ 粉紅",
  "PIBLOCKLY_HW_PS2_BUTTON": "按鈕",
  "PIBLOCKLY_HW_PS2_BUTTON_EVENT_MESSAGE": "PS2手把 按鈕 %1 %2",
  "PIBLOCKLY_HW_PS2_PRESSURES_ANALOG": "壓力靈敏度類比值",
  "PIBLOCKLY_HW_PS2_PRESSURES_READ_MESSAGE": "PS2手把 按鈕 %1 壓力靈敏度類比值",
  "PIBLOCKLY_HW_PS2_INITIAL_MESSAGE": "PS2手把 初始化 CLK %1 CMD %2 CS %3 DAT %4 壓力靈敏度 %5 振動回饋 %6",

  "PIBLOCKLY_HW_PS2_INITIAL_TOOLTIP": "初始化PS2手把感測器",
  "PIBLOCKLY_HW_PS2_READ_TOOLTIP": "讀取PS2手把的最新狀態(按鈕、搖桿)。可同時設定手把的震動馬達是否開啟，以及其震動強度(0-255)。",
  "PIBLOCKLY_HW_PS2_BUTTON_EVENT_TOOLTIP": "偵測PS2手把按鈕事件（按下、放開等）",
  "PIBLOCKLY_HW_PS2_INITIAL_FUNC_TOOLTIP": "啟用或停用PS2手把的壓力靈敏度或震動回饋功能",
  "PIBLOCKLY_HW_PS2_STICK_DIRECTION_TOOLTIP": "偵測PS2手把搖桿的方向（左搖桿或右搖桿，四向或八向）",
  "PIBLOCKLY_HW_PS2_RECEIVER_STATE_TOOLTIP": "檢查PS2手把接收器是否連接到開發板",
  "PIBLOCKLY_HW_PS2_STATE_TOOLTIP": "檢查PS2手把是否連接到開發板",
  "PIBLOCKLY_HW_PS2_ANALOG_MAX_TOOLTIP": "設定開發板的類比輸入最大值，用於PS2搖桿的讀取",
  "PIBLOCKLY_HW_PS2_ANALOG_READ_TOOLTIP": "讀取PS2手把搖桿的類比值或方位角",
  "PIBLOCKLY_HW_PS2_PRESSURES_READ_TOOLTIP": "讀取PS2手把按鈕的壓力靈敏度類比值",


  // Actuator
  // L293D Blocks
  "PIBLOCKLY_HW_ACTUATORS_L293D": "L293D",
  "PIBLOCKLY_HW_L293D_MOTOR_RUN_TITLE": "L293D 直流馬達",
  "PIBLOCKLY_HW_L293D_MOTOR_RUN_TOOLTIP": "L293D 直流馬達控制",
  "PIBLOCKLY_HW_L293D_MOTOR_RUN_MESSAGE": "L293D 直流馬達 %1 %2 速度 %3",
  "PIBLOCKLY_HW_L293D_MOTOR_STOP_TITLE": "L293D 直流馬達停止",
  "PIBLOCKLY_HW_L293D_MOTOR_STOP_TOOLTIP": "停止 L293D 直流馬達",
  "PIBLOCKLY_HW_L293D_MOTOR_STOP_MESSAGE": "L293D 直流馬達 %1 停止",
  "PIBLOCKLY_HW_L293D_STEPPER_INIT_TITLE": "L293D 步進馬達 初始化",
  "PIBLOCKLY_HW_L293D_STEPPER_INIT_TOOLTIP": "初始化L293D步進馬達",
  "PIBLOCKLY_HW_L293D_STEPPER_INIT_MESSAGE": "L293D 步進馬達 初始化 %1 步/圈 %2",
  "PIBLOCKLY_HW_L293D_STEPPER_SPEED_TITLE": "L293D 步進馬達 設定轉速(RPM)",
  "PIBLOCKLY_HW_L293D_STEPPER_SPEED_TOOLTIP": "設定L293D步進馬達轉速",
  "PIBLOCKLY_HW_L293D_STEPPER_SPEED_MESSAGE": "L293D 步進馬達 %1 設定轉速 %2 RPM",
  "PIBLOCKLY_HW_L293D_STEPPER_RUN_TITLE": "L293D 步進馬達 移動步數",
  "PIBLOCKLY_HW_L293D_STEPPER_RUN_TOOLTIP": "驅動L293D步進馬達移動指定步數",
  "PIBLOCKLY_HW_L293D_STEPPER_RUN_MESSAGE": "L293D 步進馬達 %1 %2 步數 %3 %4",
  "PIBLOCKLY_HW_L293D_STEPPER_STOP_TITLE": "L293D 步進馬達 停止",
  "PIBLOCKLY_HW_L293D_STEPPER_STOP_TOOLTIP": "停止L293D步進馬達",
  "PIBLOCKLY_HW_L293D_STEPPER_STOP_MESSAGE": "L293D 步進馬達 %1 停止",
  "PIBLOCKLY_HW_L293D_SERVO_RUN_TITLE": "L293D 伺服馬達",
  "PIBLOCKLY_HW_L293D_SERVO_RUN_TOOLTIP": "控制L293D連接的伺服馬達",
  "PIBLOCKLY_HW_L293D_SERVO_RUN_MESSAGE": "L293D 伺服馬達 %1 角度 %2",
  "PIBLOCKLY_HW_L293D_SERVO_DETACH_TITLE": "L293D 伺服馬達 分離",
  "PIBLOCKLY_HW_L293D_SERVO_DETACH_TOOLTIP": "分離L293D連接的伺服馬達",
  "PIBLOCKLY_HW_L293D_SERVO_DETACH_MESSAGE": "L293D 伺服馬達 %1 分離",
  "PIBLOCKLY_HW_L293D_DIRECTION_FORWARD": "正轉",
  "PIBLOCKLY_HW_L293D_DIRECTION_BACKWARD": "反轉",
  "PIBLOCKLY_HW_L293D_STEPPER_METHOD_SINGLE": "單相線圈",
  "PIBLOCKLY_HW_L293D_STEPPER_METHOD_DOUBLE": "雙相線圈",
  "PIBLOCKLY_HW_L293D_STEPPER_METHOD_INTERLEAVE": "交錯線圈",
  "PIBLOCKLY_HW_L293D_STEPPER_METHOD_MICROSTEP": "微步",
  "PIBLOCKLY_HW_L293D_SERVO_CHANNEL_1": "1",
  "PIBLOCKLY_HW_L293D_SERVO_CHANNEL_2": "2",

  // PCA9685 Blocks
  "PIBLOCKLY_HW_ACTUATORS_PCA9685": "PCA9685",
  "PIBLOCKLY_HW_PCA9685_INIT": "初始化 PCA9685 (I2C) SDA %1 SCL %2",
  "PIBLOCKLY_HW_PCA9685_PWM_CHANNEL": "PWM 輸出連接腳位",
  "PIBLOCKLY_HW_PCA9685_PWM_VALUE": "數值",
  "PIBLOCKLY_HW_PCA9685_PWM_WRITE_MESSAGE": "PWM 輸出連接腳位 %1 數值 %2 (0~4095)",
  "PIBLOCKLY_HW_PCA9685_TOOLTIP": "PCA9685",
  "PIBLOCKLY_HW_PCA9685_SERVO_PULSE_MIN": "設定伺服馬達脈衝寬度最小值",
  "PIBLOCKLY_HW_PCA9685_SERVO_PULSE_MAX": "最大值",
  "PIBLOCKLY_HW_PCA9685_SERVO_INIT_MESSAGE": "設定伺服馬達脈衝寬度最小值 %1 最大值 %2",
  "PIBLOCKLY_HW_PCA9685_SERVO_CHANNEL": "伺服馬達輸出連接腳位",
  "PIBLOCKLY_HW_PCA9685_SERVO_DEGREE": "角度",
  "PIBLOCKLY_HW_PCA9685_SERVO_WRITE_MESSAGE": "伺服馬達輸出連接腳位 %1 角度 %2 (0~180)",

  "PIBLOCKLY_HW_PCA9685_INIT_TOOLTIP": "初始化 PCA9685 PWM 控制器。可設定 I2C 腳位。",
  "PIBLOCKLY_HW_PCA9685_PWM_WRITE_TOOLTIP": "設定PCA9685 PWM控制器特定通道的PWM值。",
  "PIBLOCKLY_HW_PCA9685_SERVO_INIT_TOOLTIP": "設定PCA9685 PWM控制器伺服馬達的脈衝寬度最小值和最大值。",
  "PIBLOCKLY_HW_PCA9685_SERVO_WRITE_TOOLTIP": "設定PCA9685 PWM控制器特定通道的伺服馬達角度。",


  // Stepper Blocks
  "PIBLOCKLY_HW_ACTUATORS_STEPPER": "Stepper",
  "PIBLOCKLY_HW_STEPPER_INIT": "步進馬達 初始化",
  "PIBLOCKLY_HW_STEPPER_SET_SPEED": "設定轉速",
  "PIBLOCKLY_HW_STEPPER_SET_SPEED_MESSAGE": "設定轉速 %1",
  "PIBLOCKLY_HW_STEPPER_SET_ACCEL": "設定加速度",
  "PIBLOCKLY_HW_STEPPER_SET_ACCEL_MESSAGE": "設定加速度 %1",
  "PIBLOCKLY_HW_STEPPER_MOVE_TO": "移動到",
  "PIBLOCKLY_HW_STEPPER_MOVE_TO_MESSAGE": "移動到 %1",
  "PIBLOCKLY_HW_STEPPER_MOVE": "移動",
  "PIBLOCKLY_HW_STEPPER_MOVE_MESSAGE": "移動 %1 步",
  "PIBLOCKLY_HW_STEPPER_RUN": "運轉",
  "PIBLOCKLY_HW_STEPPER_STOP": "停止",
  "PIBLOCKLY_HW_STEPPER_MOTOR_LABEL": "馬達",
  "PIBLOCKLY_HW_STEPPER_INTERFACE_LABEL": "介面",
  "PIBLOCKLY_HW_STEPPER_STEPS_LABEL": "步數",
  "PIBLOCKLY_HW_STEPPER_PIN1_LABEL": "pin1",
  "PIBLOCKLY_HW_STEPPER_PIN2_LABEL": "pin2",
  "PIBLOCKLY_HW_STEPPER_PIN3_LABEL": "pin3",
  "PIBLOCKLY_HW_STEPPER_PIN4_LABEL": "pin4",
  "PIBLOCKLY_HW_STEPPER_INIT_MESSAGE": "步進馬達 初始化 馬達 %1 介面 %2 步數 %3 腳位1 %4 腳位2 %5 腳位3 %6 腳位4 %7",

  "PIBLOCKLY_HW_STEPPER_INIT_TOOLTIP": "初始化步進馬達，設定馬達類型、介面類型、步數及連接腳位。",
  "PIBLOCKLY_HW_STEPPER_SET_SPEED_TOOLTIP": "設定步進馬達的轉速（RPM）。",
  "PIBLOCKLY_HW_STEPPER_SET_ACCEL_TOOLTIP": "設定步進馬達的加速度。",
  "PIBLOCKLY_HW_STEPPER_MOVE_TO_TOOLTIP": "使步進馬達移動到指定位置。",
  "PIBLOCKLY_HW_STEPPER_MOVE_TOOLTIP": "使步進馬達移動指定的步數。",
  "PIBLOCKLY_HW_STEPPER_RUN_TOOLTIP": "使步進馬達開始運轉。",
  "PIBLOCKLY_HW_STEPPER_STOP_TOOLTIP": "停止步進馬達運轉。",



  // AI
  // HuskyLens Category
  "PIBLOCKLY_HW_CATEGORY_HUSKYLENS": "HuskyLens",

  "PIBLOCKLY_HW_HUSKYLENS_SETUP": "Setup",
  "PIBLOCKLY_HW_HUSKYLENS_READ": "Read",
  "PIBLOCKLY_HW_HUSKYLENS_TRAINING": "AI Training",
  "PIBLOCKLY_HW_HUSKYLENS_DISPLAY": "Display",
  "PIBLOCKLY_HW_HUSKYLENS_SD": "SD Card",


  // HuskyLens Blocks
  "PIBLOCKLY_HW_HUSKYLENS_INIT_TITLE": "HuskyLens I2C 初始化",
  "PIBLOCKLY_HW_HUSKYLENS_INIT_TOOLTIP": "透過 I2C 初始化 HuskyLens 感測器。可設定 I2C 腳位。需要安裝 DFRobot 的 'HUSKYLENS' 函式庫。",

  "PIBLOCKLY_HW_HUSKYLENS_UART_INIT_TITLE": "Huskylens：透過UART(序列埠)初始化",
  "PIBLOCKLY_HW_HUSKYLENS_UART_INIT_TOOLTIP": "透過UART(SoftwareSerial)初始化Huskylens感測器。需要DFRobot的'HUSKYLENS'函式庫。",
  "PIBLOCKLY_HW_HUSKYLENS_UART_INIT_MESSAGE": "Huskylens：透過UART(序列埠)初始化 RX 腳位 %1 TX 腳位 %2",

  "PIBLOCKLY_HW_HUSKYLENS_SET_ALGORITHM_TITLE": "設定 HuskyLens 演算法為",
  "PIBLOCKLY_HW_HUSKYLENS_SET_ALGORITHM_TOOLTIP": "切換 HuskyLens 當前運行的演算法。",

  "PIBLOCKLY_HW_HUSKYLENS_ALGORITHM_FACE_RECOGNITION": "人臉辨識",
  "PIBLOCKLY_HW_HUSKYLENS_ALGORITHM_OBJECT_TRACKING": "物體追蹤",
  "PIBLOCKLY_HW_HUSKYLENS_ALGORITHM_OBJECT_RECOGNITION": "物體辨識",
  "PIBLOCKLY_HW_HUSKYLENS_ALGORITHM_LINE_TRACKING": "巡線",
  "PIBLOCKLY_HW_HUSKYLENS_ALGORITHM_COLOR_RECOGNITION": "顏色辨識",
  "PIBLOCKLY_HW_HUSKYLENS_ALGORITHM_TAG_RECOGNITION": "標籤辨識",

  "PIBLOCKLY_HW_HUSKYLENS_REQUEST_AND_CHECK_TITLE": "當 HuskyLens 偵測到結果時",
  "PIBLOCKLY_HW_HUSKYLENS_REQUEST_AND_CHECK_TOOLTIP": "向 HuskyLens 請求數據，並遍歷所有偵測到的結果。",

  "PIBLOCKLY_HW_HUSKYLENS_GET_RESULT_PROPERTY_TITLE": "取得",
  "PIBLOCKLY_HW_HUSKYLENS_GET_PROPERTY_OF_RESULT": "的當前結果",
  "PIBLOCKLY_HW_HUSKYLENS_GET_RESULT_PROPERTY_TOOLTIP": "在迴圈中取得當前結果的指定屬性。",

  "PIBLOCKLY_HW_HUSKYLENS_PROPERTY_X_CENTER": "X 中心點",
  "PIBLOCKLY_HW_HUSKYLENS_PROPERTY_Y_CENTER": "Y 中心點",
  "PIBLOCKLY_HW_HUSKYLENS_PROPERTY_WIDTH": "寬度",
  "PIBLOCKLY_HW_HUSKYLENS_PROPERTY_HEIGHT": "高度",
  "PIBLOCKLY_HW_HUSKYLENS_PROPERTY_ID": "ID",

  "PIBLOCKLY_HW_HUSKYLENS_SHOW_TEXT_TITLE": "HuskyLens: 顯示文字",
  "PIBLOCKLY_HW_HUSKYLENS_SHOW_TEXT_X": "於 X",
  "PIBLOCKLY_HW_HUSKYLENS_SHOW_TEXT_Y": "Y",
  "PIBLOCKLY_HW_HUSKYLENS_SHOW_TEXT_TOOLTIP": "在 HuskyLens 螢幕的指定座標上顯示自訂文字字串。",
  "PIBLOCKLY_HW_HUSKYLENS_SHOW_TEXT_MESSAGE": "HuskyLens: 顯示文字 %1 於 X %2 Y %3",

  "PIBLOCKLY_HW_HUSKYLENS_CLEAR_SCREEN_TITLE": "HuskyLens: 清除螢幕文字",
  "PIBLOCKLY_HW_HUSKYLENS_CLEAR_SCREEN_TOOLTIP": "清除先前在 HuskyLens 螢幕上繪製的所有自訂文字。",

  "PIBLOCKLY_HW_HUSKYLENS_LEARN_TITLE": "HuskyLens: 學習物件並給予 ID",
  "PIBLOCKLY_HW_HUSKYLENS_LEARN_TOOLTIP": "命令 HuskyLens 學習當前物件並為其分配指定的 ID。",
  "PIBLOCKLY_HW_HUSKYLENS_LEARN_MESSAGE": "HuskyLens: 學習物件並給予 ID %1",

  "PIBLOCKLY_HW_HUSKYLENS_FORGET_TITLE": "HuskyLens: 忘記所有已學習的物件",
  "PIBLOCKLY_HW_HUSKYLENS_FORGET_TOOLTIP": "命令 HuskyLens 忘記所有演算法中已學習的全部物件。",

  "PIBLOCKLY_HW_HUSKYLENS_COUNT_LEARNED_TOTAL": "已學習的 ID (全部)",
  "PIBLOCKLY_HW_HUSKYLENS_COUNT_BLOCKS_SCREEN": "畫面中的方塊",
  "PIBLOCKLY_HW_HUSKYLENS_COUNT_ARROWS_SCREEN": "畫面中的箭頭",

  "PIBLOCKLY_HW_HUSKYLENS_GET_COUNT_TITLE": "HuskyLens: 取得總數",
  "PIBLOCKLY_HW_HUSKYLENS_GET_COUNT_TOOLTIP": "回傳已學習的 ID 總數，或畫面上當前偵測到的方塊/箭頭數量。",
  "PIBLOCKLY_HW_HUSKYLENS_GET_COUNT_MESSAGE": "HuskyLens: 取得總數 %1",

  "PIBLOCKLY_HW_HUSKYLENS_SET_NAME_TITLE": "HuskyLens: 設定名稱",
  "PIBLOCKLY_HW_HUSKYLENS_SET_NAME_FOR_ID": "給 ID",
  "PIBLOCKLY_HW_HUSKYLENS_SET_NAME_TOOLTIP": "為指定的已學習 ID 分配一個自訂名稱。",
  "PIBLOCKLY_HW_HUSKYLENS_SET_NAME_MESSAGE": "HuskyLens: 設定名稱 %1 給 ID %2",

  "PIBLOCKLY_HW_HUSKYLENS_SAVE_PHOTO_TITLE": "HuskyLens: 儲存畫面截圖到 SD 卡",
  "PIBLOCKLY_HW_HUSKYLENS_SAVE_PHOTO_TOOLTIP": "將目前螢幕內容作為照片儲存到 SD 卡。",
  "PIBLOCKLY_HW_HUSKYLENS_SAVE_MODEL_TITLE": "HuskyLens: 從模型欄位儲存模型到 SD 卡",
  "PIBLOCKLY_HW_HUSKYLENS_SAVE_MODEL_TOOLTIP": "從指定的模型欄位，將當前演算法的數據儲存到 SD 卡。",
  "PIBLOCKLY_HW_HUSKYLENS_SAVE_MODEL_MESSAGE": "HuskyLens: 從模型欄位儲存模型到 SD 卡 %1",

  "PIBLOCKLY_HW_HUSKYLENS_LOAD_MODEL_TITLE": "HuskyLens: 從 SD 卡載入模型到欄位",
  "PIBLOCKLY_HW_HUSKYLENS_LOAD_MODEL_TOOLTIP": "從 SD 卡讀取演算法數據，並載入到指定的模型欄位。",
  "PIBLOCKLY_HW_HUSKYLENS_LOAD_MODEL_MESSAGE": "HuskyLens: 從 SD 卡載入模型到欄位 %1",

};
